import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@arcana/auth";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const auth = new AuthProvider("xar_test_3c2a6ae9389d984a1fb8cb26fa603d33cd371f6f", {
    theme: "light",
    network: "dev",
    connectOptions: {
        compact: true,
    },
});

auth.init();

// auth.connect();

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
